version: '3.5'
services:
  mysql:
    image: mysql:5.7.35
    container_name: mysql
    restart: always
    ports:
      - 33066:3306
    volumes:
      - /home/pounds/1soft/dockerData/mysql/data:/usr/local/mysql
      - /home/pounds/1soft/dockerData/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /home/pounds/1soft/dockerData/mysql/logs:/usr/local/mysql/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password #这个是为了解决无法远程登录

